-- Print settings columns for configurable document layout preferences
ALTER TABLE public.tblsettings
  ADD COLUMN IF NOT EXISTS "printPaperSize"          TEXT DEFAULT 'A4',
  ADD COLUMN IF NOT EXISTS "printShowLogo"           TEXT DEFAULT 'true',
  ADD COLUMN IF NOT EXISTS "printLogoVariant"        TEXT DEFAULT 'light',
  ADD COLUMN IF NOT EXISTS "printFooterText"         TEXT,
  ADD COLUMN IF NOT EXISTS "printQuoteHeaderColor"   TEXT DEFAULT '#0f9cdf',
  ADD COLUMN IF NOT EXISTS "printQuoteShowTerms"     TEXT DEFAULT 'true',
  ADD COLUMN IF NOT EXISTS "printQuoteShowMisc"      TEXT DEFAULT 'false',
  ADD COLUMN IF NOT EXISTS "printQuoteShowValidity"  TEXT DEFAULT 'true',
  ADD COLUMN IF NOT EXISTS "printSoShowDiscount"     TEXT DEFAULT 'false',
  ADD COLUMN IF NOT EXISTS "printSoShowPaymentTerms" TEXT DEFAULT 'true',
  ADD COLUMN IF NOT EXISTS "printSoShowSerials"      TEXT DEFAULT 'true',
  ADD COLUMN IF NOT EXISTS "printDrShowSerials"      TEXT DEFAULT 'true',
  ADD COLUMN IF NOT EXISTS "printDrShowSignature"    TEXT DEFAULT 'true',
  ADD COLUMN IF NOT EXISTS "printReportShowHeader"   TEXT DEFAULT 'true',
  ADD COLUMN IF NOT EXISTS "printCvShowPreparedBy"   TEXT DEFAULT 'true',
  ADD COLUMN IF NOT EXISTS "printCvShowSignatureLine" TEXT DEFAULT 'false',
  ADD COLUMN IF NOT EXISTS "printAddressDetails"      TEXT,
  ADD COLUMN IF NOT EXISTS "printAddressShowSoInvoice" TEXT DEFAULT 'true',
  ADD COLUMN IF NOT EXISTS "printAddressShowQuotation" TEXT DEFAULT 'true',
  ADD COLUMN IF NOT EXISTS "printAddressShowDr"        TEXT DEFAULT 'true',
  ADD COLUMN IF NOT EXISTS "printAddressShowAccounting" TEXT DEFAULT 'true',
  ADD COLUMN IF NOT EXISTS "printSignaturePreparedBy" TEXT,
  ADD COLUMN IF NOT EXISTS "printSignatureCheckedBy"  TEXT,
  ADD COLUMN IF NOT EXISTS "printSignatureApprovedBy" TEXT;
