ALTER TABLE IF EXISTS tblpo_payments
  ADD COLUMN IF NOT EXISTS bank_name TEXT,
  ADD COLUMN IF NOT EXISTS reference_no TEXT,
  ADD COLUMN IF NOT EXISTS check_no TEXT,
  ADD COLUMN IF NOT EXISTS cheque_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS issued_by TEXT;